### ISSUE TITLE
Invalid timezone 'UTC' on HHVM

### ISSUE THREAD

**Issue by steelbrain** [braintree/braintree_php#100]
Not yet tested on PHP. Here's a trace
```
Someday, 00-Abc-00 00:00:00 GMT: Exception caught at Top Level
Exception { DateTimeZone::__construct(): Unknown or bad timezone (UTC) }
    #0 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Xml/Parser.php(128): DateTimeZone->__construct()
    #1 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Xml/Parser.php(93): Braintree_Xml_Parser::_timestampToUTC()
    #2 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Xml/Parser.php(70): Braintree_Xml_Parser::_nodeToValue()
    #3 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Xml/Parser.php(110): Braintree_Xml_Parser::_nodeToArray()
    #4 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Xml/Parser.php(24): Braintree_Xml_Parser::_nodeToValue()
    #5 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Xml.php(26): Braintree_Xml_Parser::arrayFromXml()
    #6 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Http.php(43): Braintree_Xml::buildArrayFromXml()
    #7 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/TransactionGateway.php(402): Braintree_Http->post()
    #8 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/TransactionGateway.php(45): Braintree_TransactionGateway->_doCreate()
    #9 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/TransactionGateway.php(250): Braintree_TransactionGateway->create()
    #10 /var/web/PublishSpace/HG/External/braintree/lib/Braintree/Transaction.php(470): Braintree_TransactionGateway->sale()

```

**Comment by matthewpatterson** [comment]
Hey @steelbrain, can you let us know which version of the braintree_php library you are using, as well as which version of HHVM you are using?

**Comment by steelbrain** [comment]
HHVM version is 3.9. braintree library is at v3.5.0.

**Comment by raymondberg** [comment]
Hi, @steelbrain! We've seen issues like this before. You might want to check out [issue #65](https://github.com/braintree/braintree_php/issues/65) to see if this applies to you. If this doesn't help, you may want to  [contact Braintree support](https://support.braintreepayments.com) and provide more detailed information about your PHP environment and OS. 

I'm going to close this for now, but please reopen if you believe this might be an issue with the code itself after trying these solutions.
